# Generated by Django 3.1.4 on 2022-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=288)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Env_science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=288)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Human_Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=288)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Psychology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=288)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=288)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='World_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=288)),
                ('notes', models.TextField(default='')),
            ],
        ),
    ]
