# Generated by Django 3.1.4 on 2022-11-09 22:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20221107_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economics',
            name='notes',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AlterField(
            model_name='env_science',
            name='notes',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AlterField(
            model_name='human_geography',
            name='notes',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AlterField(
            model_name='psychology',
            name='notes',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='notes',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AlterField(
            model_name='world_history',
            name='notes',
            field=mdeditor.fields.MDTextField(null=True),
        ),
    ]
