# Generated by Django 4.1.3 on 2023-01-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_economics_notes_alter_env_science_notes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Economics',
            new_name='Macroeconomics',
        ),
        migrations.RenameModel(
            old_name='Seminar',
            new_name='US_hisotry',
        ),
    ]
