# Generated by Django 4.1.3 on 2022-12-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=1024, verbose_name='题干内容')),
                ('type', models.IntegerField(choices=[(0, '单选'), (1, '多选')], verbose_name='题目类型,单选还是多选')),
            ],
            options={
                'verbose_name': '题库',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='选项ABCDEFGH')),
                ('content', models.CharField(max_length=256, verbose_name='选项内容')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject')),
            ],
            options={
                'verbose_name': '选项表',
                'db_table': 'options',
                'ordering': ['options'],
                'unique_together': {('subject', 'content')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='正确答案ABCDEFGH')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject')),
            ],
            options={
                'verbose_name': '答案表',
                'db_table': 'answer',
                'ordering': ['options'],
                'unique_together': {('subject', 'options')},
            },
        ),
    ]
