# Generated by Django 4.1.3 on 2022-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Exam_Question'},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='stem',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(default='answer', max_length=256),
        ),
        migrations.AddField(
            model_name='options',
            name='title',
            field=models.CharField(default='option', max_length=256),
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default='subject', max_length=256),
        ),
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='正确答案ABCDE'),
        ),
        migrations.AlterField(
            model_name='options',
            name='content',
            field=models.TextField(verbose_name='选项内容'),
        ),
        migrations.AlterField(
            model_name='options',
            name='options',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='选项ABCDE'),
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
    ]
