# Generated by Django 4.1.3 on 2022-12-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_answer_options_alter_options_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='科目')),
                ('title', models.TextField(verbose_name='题目')),
                ('optionA', models.CharField(max_length=258, verbose_name='A选项')),
                ('optionB', models.CharField(max_length=258, verbose_name='B选项')),
                ('optionC', models.CharField(max_length=258, verbose_name='C选项')),
                ('optionD', models.CharField(max_length=258, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10, verbose_name='答案')),
            ],
            options={
                'verbose_name': '单项选择题库',
                'verbose_name_plural': '单项选择题库',
                'db_table': 'question',
            },
        ),
        migrations.AlterUniqueTogether(
            name='options',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='options',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
