# Generated by Django 4.1.3 on 2022-12-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_question_alter_options_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optionE',
            field=models.CharField(default='', max_length=258, verbose_name='E选项'),
        ),
    ]
