# Generated by Django 4.1.3 on 2023-01-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_optione'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explain',
            field=models.TextField(blank=True, verbose_name='题目解析'),
        ),
    ]
